#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# deploy.sh — One-command deployment for Intelligent Investor V2
#             Targets: Hostinger VPS running Ubuntu 22.04 / 24.04
#
# Usage (run on the VPS as root or with sudo):
#   ./deploy.sh <domain> <email> [--skip-ssl]
#
# Examples:
#   ./deploy.sh app.intelligentinvestor.io admin@example.com
#   ./deploy.sh app.intelligentinvestor.io admin@example.com --skip-ssl
#
# What it does:
#   1. Installs Docker + Docker Compose plugin (if missing)
#   2. Creates .env with generated secrets (skips if .env already exists)
#   3. Starts PostgreSQL + app containers (HTTP mode)
#   4. Obtains a Let's Encrypt TLS certificate via Certbot
#   5. Activates the full SSL Nginx config and reloads Nginx
#   6. Sets up daily cert auto-renewal cron job
#
# After first deploy, update the app with:
#   git pull && docker compose up -d --build app
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

DOMAIN="${1:-}"
EMAIL="${2:-}"
SKIP_SSL="${3:-}"

# ── Validate args ─────────────────────────────────────────────────────────────
if [[ -z "$DOMAIN" || -z "$EMAIL" ]]; then
    echo "Usage: $0 <domain> <email> [--skip-ssl]"
    echo "  domain  — your app domain, e.g. app.intelligentinvestor.io"
    echo "  email   — used for Let's Encrypt expiry notices"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
step() { echo -e "\n${BLUE}▶  $1${NC}"; }
ok()   { echo -e "${GREEN}✓  $1${NC}"; }
warn() { echo -e "${YELLOW}⚠  $1${NC}"; }
die()  { echo -e "${RED}✗  $1${NC}"; exit 1; }

# ─────────────────────────────────────────────────────────────────────────────
# 1. Install Docker + Docker Compose
# ─────────────────────────────────────────────────────────────────────────────
step "Checking Docker installation"

if ! command -v docker &>/dev/null; then
    step "Installing Docker (Ubuntu)"
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg lsb-release

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
       https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
      > /etc/apt/sources.list.d/docker.list

    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
        docker-buildx-plugin docker-compose-plugin

    systemctl enable --now docker
    ok "Docker installed"
else
    ok "Docker already installed: $(docker --version)"
fi

if ! docker compose version &>/dev/null; then
    die "Docker Compose plugin not found. Install docker-compose-plugin via apt."
fi
ok "Docker Compose: $(docker compose version --short)"

# ─────────────────────────────────────────────────────────────────────────────
# 2. Create .env if it doesn't exist
# ─────────────────────────────────────────────────────────────────────────────
step "Configuring environment"

if [[ -f ".env" ]]; then
    warn ".env already exists — skipping generation. Edit it manually if needed."
else
    # Generate cryptographically random secrets
    DB_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 40)
    JWT_SECRET=$(openssl rand -hex 32)

    cat > .env <<ENVEOF
# ── Intelligent Investor V2 — Production Environment ─────────────
# Generated by deploy.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# Keep this file secret — never commit to git.

# ── Database ──────────────────────────────────────────────────────
# DB_PASSWORD is used by docker-compose.yml to configure the DB
# container AND to build DATABASE_URL for the app container.
DB_PASSWORD=${DB_PASSWORD}
# DATABASE_URL is overridden by docker-compose.yml to use the 'db'
# service hostname. This value is for reference / local psql access.
DATABASE_URL=postgresql://ii_user:${DB_PASSWORD}@localhost:5432/intelligentinvestor

# ── JWT ───────────────────────────────────────────────────────────
# Do NOT change this after users have active sessions — it logs them all out.
JWT_SECRET=${JWT_SECRET}
JWT_ALGORITHM=HS256

# ── Stripe Payments ───────────────────────────────────────────────
STRIPE_SECRET_KEY=sk_live_REPLACE_ME
STRIPE_PUBLISHABLE_KEY=pk_live_REPLACE_ME
STRIPE_WEBHOOK_SECRET=whsec_REPLACE_ME

STRIPE_PRICE_STARTER_MONTHLY=price_REPLACE_ME
STRIPE_PRICE_STARTER_YEARLY=price_REPLACE_ME
STRIPE_PRICE_PRO_MONTHLY=price_REPLACE_ME
STRIPE_PRICE_PRO_YEARLY=price_REPLACE_ME
STRIPE_PRICE_ANALYST_MONTHLY=price_REPLACE_ME
STRIPE_PRICE_ANALYST_YEARLY=price_REPLACE_ME
STRIPE_PRICE_ENTERPRISE_MONTHLY=price_REPLACE_ME
STRIPE_PRICE_ENTERPRISE_YEARLY=price_REPLACE_ME

# ── AI Analysis ───────────────────────────────────────────────────
ANTHROPIC_API_KEY=sk-ant-REPLACE_ME

# ── Stock Data ────────────────────────────────────────────────────
FMP_API_KEY=REPLACE_ME

# ── Email (Gmail SMTP) ────────────────────────────────────────────
GMAIL_FROM=REPLACE_ME@gmail.com
GMAIL_APP_PASSWORD=REPLACE_ME

# ── Application ───────────────────────────────────────────────────
APP_BASE_URL=https://${DOMAIN}
PORT=5050

# ── Admin ─────────────────────────────────────────────────────────
ADMIN_EMAIL=${EMAIL}
ENVEOF

    chmod 600 .env
    ok ".env created with generated DB_PASSWORD and JWT_SECRET"
    warn "Edit .env to fill in your Stripe / Anthropic / FMP keys before going live."
fi

# Source the env so we can use $DB_PASSWORD below
set -o allexport
source .env
set +o allexport

# ─────────────────────────────────────────────────────────────────────────────
# 3. Start services in HTTP mode (no SSL yet)
# ─────────────────────────────────────────────────────────────────────────────
step "Building and starting containers (HTTP mode)"

# Make sure we're using the HTTP-only nginx config
cp nginx/nginx.conf nginx/nginx.conf.bak 2>/dev/null || true

docker compose pull --quiet nginx certbot 2>/dev/null || true
docker compose build --quiet app

docker compose up -d db
echo "   Waiting for PostgreSQL to be healthy…"
RETRIES=0
until docker compose exec db pg_isready -U ii_user -d intelligentinvestor -q 2>/dev/null; do
    RETRIES=$((RETRIES+1))
    [[ $RETRIES -gt 30 ]] && die "PostgreSQL did not become healthy in 60s"
    sleep 2
done
ok "PostgreSQL healthy"

docker compose up -d app nginx
echo "   Waiting for app to be healthy (schema init may take ~20s on first boot)…"
RETRIES=0
until curl -sf "http://localhost/health" | grep -q '"db":{"status":"ok"}' 2>/dev/null; do
    RETRIES=$((RETRIES+1))
    [[ $RETRIES -gt 40 ]] && die "App did not become healthy in 80s — check: docker compose logs app"
    sleep 2
done
ok "App healthy at http://${DOMAIN}"

# ─────────────────────────────────────────────────────────────────────────────
# 4. Obtain Let's Encrypt certificate
# ─────────────────────────────────────────────────────────────────────────────
if [[ "$SKIP_SSL" == "--skip-ssl" ]]; then
    warn "Skipping SSL (--skip-ssl passed). The app is running on HTTP."
    warn "Run without --skip-ssl to add HTTPS."
else
    step "Obtaining Let's Encrypt certificate for ${DOMAIN}"

    DOMAIN="$DOMAIN" CERTBOT_EMAIL="$EMAIL" \
        docker compose --profile certbot run --rm certbot

    CERT_PATH="/etc/letsencrypt/live/${DOMAIN}/fullchain.pem"
    if docker compose exec nginx test -f "$CERT_PATH" 2>/dev/null; then
        ok "Certificate obtained"
    else
        # Check inside the certbot_certs volume via a temp container
        if docker run --rm -v "$(basename $SCRIPT_DIR)_certbot_certs:/certs" alpine \
               test -f "/certs/live/${DOMAIN}/fullchain.pem" 2>/dev/null; then
            ok "Certificate obtained (in volume)"
        else
            die "Certificate not found. Check DNS: dig +short A ${DOMAIN} should return this VPS IP."
        fi
    fi

    # ── 5. Switch to SSL Nginx config ──────────────────────────────
    step "Activating SSL Nginx configuration"

    # Substitute DOMAIN placeholder in the SSL config
    sed "s/DOMAIN/${DOMAIN}/g" nginx/nginx.ssl.conf > nginx/nginx.conf

    # Reload Nginx with the new config (no downtime)
    docker compose exec nginx nginx -t && docker compose exec nginx nginx -s reload
    ok "Nginx reloaded with SSL — https://${DOMAIN} is live"

    # ── 6. Auto-renewal cron ────────────────────────────────────────
    step "Setting up certificate auto-renewal"

    CRON_CMD="0 3 * * * cd ${SCRIPT_DIR} && DOMAIN=${DOMAIN} CERTBOT_EMAIL=${EMAIL} docker compose --profile certbot run --rm certbot renew --quiet && docker compose exec nginx nginx -s reload"

    # Add cron job only if it doesn't already exist
    (crontab -l 2>/dev/null | grep -qF "certbot renew") \
        || (crontab -l 2>/dev/null; echo "$CRON_CMD") | crontab -
    ok "Auto-renewal cron added (runs daily at 03:00)"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Intelligent Investor V2 is deployed!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo "  App URL   : https://${DOMAIN}"
echo "  Health    : https://${DOMAIN}/health"
echo "  Logs      : docker compose logs -f app"
echo "  DB shell  : docker compose exec db psql -U ii_user intelligentinvestor"
echo ""
echo "  Next steps:"
echo "  1. Fill in Stripe / Anthropic / FMP keys in .env"
echo "  2. docker compose up -d   (to apply .env changes)"
echo "  3. Set ADMIN_EMAIL in .env and re-deploy to auto-grant admin"
echo ""
echo "  Update app in future:"
echo "  git pull && docker compose up -d --build app"
echo ""
